---

- name: Disabling IPv6
  hosts: fihe7oraprdl001
  become: true
  gather_facts: no

  tasks:

  - name: Modifying /etc/sysctl.cong for net.ipv6.conf.all.disable_ipv6
    sysctl: 
      name: net.ipv6.conf.all.disable_ipv6
      value: '1'
      state: present
      reload: yes

  - name: Modifying /etc/sysctl.cong for net.ipv6.conf.default.disable_ipv6
    sysctl: 
      name: net.ipv6.conf.default.disable_ipv6
      value: '1'
      state: present
      reload: yes

...
