---

- name: Installing required packages
  hosts: fihe7oraprdl001
  become: true
  gather_facts: no

  tasks:

  - name: Executing dnf command
    dnf:
      name: "{{item}}"
      state: latest
    with_items:
    - elfutils-libelf.i686
    - elfutils-libelf-devel.i686
    - fontconfig-devel.i686
    - glibc.i686
    - glibc-devel.i686
    - libaio.i686
    - libaio-devel.i686
    - libXrender.i686
    - libX11.i686
    - libXau.i686
    - libXi.i686
    - libXtst.i686
    - libgcc.i686
    - libnsl.i686
    - librdmacm.i686
    - libstdc++.i686
    - libstdc++-devel.i686
    - libxcb.i686
    - libibverbs.i686
    ignore_errors: yes

...


